### ISSUE TITLE
Implement as a dax for command line arguments

### ISSUE THREAD

**Issue by sttk** [sttk/cliargdax#14]
- Add `CliDaxSrc` struct type.
    - One of it's constructor functions can receive no argument.
    - One of it's constructor functions can receive a `OptCfg` array as its argument.
    - One of it's constructor functions can receive an option store as its argument.
    - It has `CreateConn` method which instantiates `CliDaxConn` and passes a `OptCfg` array or an option store to it.
- Add `CliDaxConn` struct type.
    - It has a method which provides original command line arguments.
    - it has a method which provides a `Args` which is the result of `ParseWith` function.
    - It has a method which provides an option store which is the result of `ParseFor` funcition.
    - It has a method which provides a `OptCfg` array.
    - it has a method which provices `Parse` function to be able to parse command line arguments by programmers.
    - it has a method which executes `ParseWith` function to be able to parse command line arguments by programmers.
    - it has a method which executes `ParseFor` function to be able to parse command line arguments by programmers.
    - it has a method which executes `MakeOptCfgsFor` function to be able to parse command line arguments by programmers.
    - It has a method which executes `PrintHelp` function to be able to print command line help by programmers.

----

### Task division
- [ ] Creates empty `DaxSrc` and `DaxConn`.
- [ ] Adds `RawArgs` which returns the original command line arguments to `CliDaxConn`.
- [ ] Adds `NewCliDaxSrcWithParse()` which executes `libarg.Parse` to `CliDaxSrc`
- [ ] Adds `NewCliDaxSrcWithParseBy(optCfgs []OptCfg)` which executes `libarg.ParseBy` to `CliDaxSrc`
- [ ] Adds `NewCliDaxSrcWithParseFor(options T)` which executes `libarg.ParseFor` to `CliDaxSrc`
    - Can use generics?
- ...
